; PlatformIO Project Configuration File

[platformio]

default_envs = bluepill_f103c8


[env:bluepill_f103c8]

platform = ststm32

board = bluepill_f103c8

framework = stm32cube

monitor_speed = 115200


lib_deps =
    mincrmatt12/STM32Cube Middleware-FreeRTOS
    freertos_port_patch

custom_freertos_config_location = include/FreeRTOSConfig.h

custom_freertos_features = event_groups


[env:native]

platform = native

test_framework = unity

test_build_src = yes

build_src_filter =
    -<*>
    +<*_logic.cpp>

platform_packages =
    platformio/toolchain-gccmingw32

extra_scripts =
    pre:scripts/native_toolchain.py